name: media_picker_plus_example
description: "Demonstrates how to use the media_picker_plus plugin."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  media_picker_plus:
    path: ../
  cupertino_icons: ^1.0.8
  video_player: ^2.7.2
  photo_view: ^0.14.0
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  camerawesome: ^2.4.0
  permission_handler: ^11.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
