name: media_picker_plus
description: A Flutter plugin to pick or capture images and videos with quality control options
version: 1.1.0-rc.5
homepage: https://github.com/thanhtunguet/media_picker_plus

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: info.thanhtunguet.media_picker_plus
        pluginClass: MediaPickerPlusPlugin
        fileName: MediaPickerPlusPlugin.kt
      ios:
        pluginClass: MediaPickerPlusPlugin
        fileName: MediaPickerPlusPlugin.swift
      macos:
        pluginClass: MediaPickerPlusPlugin
        fileName: MediaPickerPlusPlugin.swift
      web:
        pluginClass: MediaPickerPlusWeb
        fileName: media_picker_plus_web.dart
